from flask import Flask, request, jsonify
from flask_cors import CORS
import threading
import time
from system_control import SystemController
import pyttsx3

app = Flask(__name__)
CORS(app)  # Allow frontend to communicate

# Initialize TTS Engine (server-side backup)
def speak_server_side(text):
    def _speak():
        engine = pyttsx3.init()
        engine.say(text)
        engine.runAndWait()
    threading.Thread(target=_speak).start()

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "online", "system": SystemController.get_system_status()})

@app.route('/process_command', methods=['POST'])
def process_command():
    data = request.json
    command = data.get('command', '').lower()
    
    response_text = ""
    action_performed = None

    # Logic Router
    if "time" in command:
        status = SystemController.get_system_status()
        response_text = f"The time is {status['time']}"
        
    elif "date" in command:
        status = SystemController.get_system_status()
        response_text = f"Today is {status['date']}"
        
    elif "battery" in command:
        status = SystemController.get_system_status()
        response_text = f"Battery is at {status['battery']}%"
        
    elif "volume" in command:
        if "up" in command or "increase" in command:
            SystemController.set_volume("up")
            response_text = "Volume increased"
        elif "down" in command or "decrease" in command:
            SystemController.set_volume("down")
            response_text = "Volume decreased"
        elif "mute" in command:
            SystemController.set_volume("mute")
            response_text = "Muted"
            
    elif "open" in command or "start" in command:
        app_name = command.replace("open", "").replace("start", "").strip()
        response_text = SystemController.open_app(app_name)
        
    elif "joke" in command:
        response_text = SystemController.get_joke()
        
    elif "screenshot" in command:
        path = SystemController.take_screenshot()
        response_text = f"Screenshot saved to Pictures"
        
    # --- WEB & INTELLIGENCE ---
    elif "play" in command:
        song = command.replace('play', '').strip()
        import pywhatkit
        pywhatkit.playonyt(song)
        response_text = f"Playing {song} on YouTube"
        
    elif "search for" in command or "google" in command:
        query = command.replace("search for", "").replace("google", "").strip()
        import webbrowser
        webbrowser.open(f"https://www.google.com/search?q={query}")
        response_text = f"Searching Google for {query}"
        

    elif any(q in command for q in ["who is", "what is", "tell me about", "who are", "what are", "define", "explain", "when was", "where is", "why is"]):
        import wikipedia
        # Remove common triggers to extract the query
        triggers = ["who is", "what is", "tell me about", "who are", "what are", "define", "explain", "when was", "where is", "why is"]
        query = command
        for trigger in triggers:
            query = query.replace(trigger, "")
        query = query.strip()
        
        try:
            # Set language to english
            wikipedia.set_lang("en")
            # Get summary
            summary = wikipedia.summary(query, sentences=2)
            response_text = summary
        except wikipedia.exceptions.DisambiguationError:
            response_text = f"There are many things named {query}. Can you be more specific?"
        except wikipedia.exceptions.PageError:
            response_text = f"I couldn't find any information on {query}."
        except Exception as e:
            print(f"Wiki Error: {e}")
            response_text = "I had trouble accessing my knowledge base."

    else:
        # Persona / Small Talk
        from persona import BellPersona
        response_text = BellPersona.get_response(command)

    # --- EMOTIONAL WRAPPER ---
    # We analyze the INPUT command sentiment, and wrap the OUTPUT response
    from persona import BellPersona
    sentiment = BellPersona.get_sentiment(command)
    
    # Don't wrap if it's already a persona response (which handles its own)
    is_persona_reply = "else" in str(action_performed) or (not any(k in command for k in ["time", "date", "battery", "volume", "open", "start", "joke", "screenshot", "play", "search", "who is", "what is"]))
    
    # Actually, simpler logic:
    # If the response was generated by specific logic blocks (time, open, etc), enrich it.
    # If it came from the 'else' block (BellPersona.get_response), it might already be enriched or we leave it.
    
    # Let's just wrap everything unless it's the fallback
    if "I didn't quite catch that" not in response_text:
         response_text = BellPersona.enrich_response(response_text, sentiment)


    return jsonify({
        "response": response_text,
        "action": action_performed,
        "status": SystemController.get_system_status(),
        "sentiment": sentiment
    })

if __name__ == '__main__':
    app.run(debug=True, port=5000)
